-- ANALİTİK SORGULAR
-- ÇALIŞANIN ADI, MAAŞI , KÜMÜLATİF TOLAMINI (ÇALIŞAN ADINA GÖRE SIRALANSIN)
-- ÇALIŞAN ADI, MAAŞI , BÖLÜMÜ , KÜMÜLATİF TOPLAMI (BÖLÜME GÖRE GRUPLANSIN MAAŞA GÖRE SIRALANSIN)
-- 1. SORU ÇÖZÜMÜ
SELECT FIRST_NAME,SALARY, SUM(SALARY) OVER (ORDER BY FIRST_NAME) AS TOPLAMMAAS
FROM EMPLOYEES ; -- İSTENİLEN GERÇEKLEŞTİ TÜM MAAŞLAR BİR ÖNCEKİ MAAŞLAR İLE TOPLANARAK GÖSTERİLDİ YA HEPSİ İSTENİLMEZSE ?
 -- 2. SORU ÇÖZÜMÜ
 SELECT FIRST_NAME, SALARY,DEPARTMENT_ID, SUM (SALARY) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY) AS SUMTOTAL
 FROM EMPLOYEES 
 ORDER BY DEPARTMENT_ID ;
-- EĞER TÜM TOPLAMI DEĞİL DE BÖLÜMSEL ŞEKLİNDE AYRI İSTİYORSAK OVER 'I PARTITION ŞEKLİNDE KULLANMALIYIZ 
-- İLK SORUDA BİR GRUPLAMA İSTENMEDİĞİ İÇİN DİREKT OVER İLE HALLETTİK ANCAK ŞİMDİ BÖLÜME GÖRE İSTEDİĞİ İÇİN PARTITION 
-- KULLANMAK ZORUNDA KALDIK Kİ BU YAPILAN İŞLEME DE İSİM VERİYORUZ İKİ ÖRNEKTE DE VERDİĞİMİZ GİBİ.