-- ANSI FORMAT
SELECT
E.LAST_NAME,
E.DEPARTMENT_ID,
D.DEPARTMENT_NAME,
L.CITY
FROM EMPLOYEES E 
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L ON D.LOCATION_ID =L.LOCATION_ID
ORDER BY E.LAST_NAME;
-- BURADA ÖNCELİKLE JOINI DEPARTMENT_ID ÜZERİNDEN DAHA SONRA DA LOCATION_ID
-- ÜZERİNDEN YAPTIK ÇÜNKÜ EMPLOYEES'İ DEPARTA DAHA SONRA DA DEPARTI LOCATİONA
-- BAĞLAMAMIZ GEREKLİYDİ. ASLINDA BURADA MANTIK ŞÖYLE BİRLEŞTİRECEĞİMİZ İKİ KOLON
-- DIŞARDAN GELİYOR EMPLOYEES DIŞINDAN YANİ BİRİSİ DEP BİRİSİ LOC'DAN GELİYOR VE BİZ 
-- BUNLARI JOINLIYORUZ. JOINLEMEK İÇİN DE ORTAK NOKTALAR OLAN ID KOLONLARINI KULLANIYORUZ.