-- CASE 
SELECT LAST_NAME, DEPARTMENT_ID, CASE DEPARTMENT_ID
WHEN 60 THEN 'MUHASABE'
WHEN 20 THEN 'ARAŞTIRMA'
WHEN 80 THEN 'INSAN KAYNAKLARI'
WHEN 40 THEN 'BİLGİ TEKNOLOJİLERİ'
ELSE 'DİĞER'
END AS DEPARTMENT FROM EMPLOYEES ; -- IF SORGUSU GİBİ ÇALIŞIR EĞER DEP ID 60 İSE MUHASEBE VE LİSTE DIŞI İSE DİĞER YAZARAK GÖSTERDİK