-- COLUMN_SEV_SUBQUERIES
-- EMPLOYEE_ID, LAST_NAME, DEPARTMENT_NAME ŞEKLİNDE KOLONLARI OLAN TABLO OLUŞTURALIM
-- İLKİNİ ANSI FORMATINDA YAPALIM
SELECT E.EMPLOYEE_ID,E.LAST_NAME,D.DEPARTMENT_NAME 
FROM EMPLOYEES E  INNER JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
ORDER BY LAST_NAME ; 

-- ŞIMDI COLUMN SEVİYESİNDE SUBQUERIES FORMATINDA YAPALIM
SELECT E.EMPLOYEE_ID,E.LAST_NAME,
(SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) DEPT_NAME
FROM EMPLOYEES E ORDER BY LAST_NAME ;
-- ANSI DE GELEN KOLON INNER JOIN İÇİNDE TANIMLANIRKEN SUBQUERIES DE AYRI BIR SELECT ICINDE TANIMLANIR

