-- DELETE KOMUTU
 DELETE FROM EMPLOYEES_COPY ; -- EMPLOYEES_COPY ADINDAKİ TABLOYU SİLER ANCAK KALICI OLARAK
 -- DEĞİL EĞER COMMİT VEYA ARDINDA DDL İŞLEMİ YAPARSAK KALICI OLARAK SİLER
 -- DİYELİM Kİ SİLDİK ŞİMDİ TEKRAR BİR KOPYA OLUŞTURALIM EMPLOYEES TABLOSUNDAN
 INSERT INTO EMPLOYEES_COPY SELECT * FROM EMPLOYEES ; -- BU ŞEKİLDE KOPYASI YAZDIRILDI
 -- DİYELİM Kİ 60 DEPARTMAN NO'LU KİŞİNİN VERİLERİNİ SİLELİM
 DELETE FROM EMPLOYEES_COPY WHERE DEPARTMENT_ID = 60 ; -- BU ŞEKİLDE 60 NO'LU KİŞİNİN VERİLERİ SİLİNİR.
 -- NOT ! R VEYA / İLE CMD'DE SON YAPILAN İŞLEMİ ÇALIŞTIRABİLİRİZ.