-- FONKSIYONLAR 1
SELECT DEPARTMENT_NAME, LOWER(DEPARTMENT_NAME), UPPER(DEPARTMENT_NAME),
INITCAP(DEPARTMENT_NAME), SUBSTR(DEPARTMENT_NAME, 5 ,3 ), LENGTH(DEPARTMENT_NAME) FROM DEPARTMENTS;
-- SEÇTİĞİMİZ KOLONUN BAŞINA FONKSİYONU UYGULUYORUZ , ÖRNEĞİN LOWER TÜM HARFLERİ KÜÇÜLTÜYLOR , UPPER BÜYÜTÜYOR
-- INITCAP SADECE BAŞ HARFLERİNİ BÜYÜTÜYOR, SUBSTR İSE BELİRTİLEN ŞEKLİNDE KISALTMA YAPIYOR. LENGTH İSE UZUNLUKLARINI
-- İFADE EDİYOR.