-- HIYERARSIK SORGULAR
-- CONNECT BY PRIOR ORNEGI (CALISANLAR İLE YONETİCİLER ARASINDAKİ HİYERARŞİ İLİŞKİSİ)
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID FROM EMPLOYEES
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID; -- BU ŞEKİLDE KULLANARAK EMPLOYEE_ID VE MANAGER_ID İ BİRBİRİNE İLİŞKİLENDİRDİK
-- LEVEL ÖRNEĞİ ( ÇALIŞANLAR İLE YÖNETİCİLER ARASINDAKİ HİYERARŞİ İLİŞKİSİ)
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID,LEVEL FROM EMPLOYEES
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID; -- BU DA ARASINDAKİ İLİŞKİYİ BOZMADAN SEVİYE EKLEYEREK GÖSTERİM YAPIYOR.
-- START WITH ÖRNEĞİ (HİYERARŞİYİ BELİRLİ BİR NOKTADAN BAŞLATABİLİRİZ) AYRICA SIBLINGS
-- KELİMESİ KULLANARAK HİYERARŞİK SIRALAMA YAPABİLİRİZ
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID,LEVEL FROM EMPLOYEES
START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID; -- BU ŞEKİLDE DE EMPLOYE_ID'NİN 100 DEN BAŞLAMASINI İSTİYORUZ.
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID ,LEVEL FROM EMPLOYEES
START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
ORDER SIBLINGS BY LAST_NAME; -- SIBLINGS KULLANMAZSAK YAPTIĞIMIZ İŞLEMLERİ BİR KENARA BIRAKIP LAST NAME' E GÖRE BİR 
-- SIRALAMA YAPACAKTI ANCAK SIBLINGS KULLANARAK YAPTIĞIMIZ İŞLEMLERİ DE DAHİL EDEREK LAST_NAME SIRALAMASI YAPMASINI İSTEDİK
-- CONNECT BY ROOT - SYS_CONNECT BY PATH ÖRNEĞİ ( HER ÇALIŞANIN HİYERARŞİDE BAĞLI OLDĞU ÜST BİRİM VE SEVİYESİ)
SELECT LAST_NAME CALISAN, CONNECT_BY_ROOT LAST_NAME YONETICI,
LEVEL -1 SEVİYE, SYS_CONNECT_BY_PATH(LAST_NAME,'-->')PATH FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60 AND LEVEL >1
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID ; -- SYS_CONNECT_BY_PATH İLE BURADAN PARENT CHİLD İLİŞKİSİNİ DAHA NET GÖRÜRÜZ.
-- SELECT İLE FROM ARASINA LEVEL YERLEŞTİRDİK VE YANINA DA SYS... PATH BAĞLANTISINI YAPTIK IF GİBİ ÇALIŞAN WHERE İLE DE 
--BELİRLİ BİR ALAN ÜZERİNDE SORGUMUZU ÇALIŞTIRDIK VE BUNU CONNECT BY İLE EMPLOYEE_ID İLE MANAGER_ID BAĞINTISINI KULLANDIK