-- INTERSECT ILE MINUS
SELECT * FROM DEPARTMENTS ORDER BY DEPARTMENT_ID;
CREATE TABLE DEPT1
AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID <= 90;

CREATE TABLE DEPT2
AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID >= 40;
-- BU ŞEKİLDE TABLOYU İKİYE BÖLÜYORUZ DEPT 1 VE İKİ DİYE
-- ŞİMDİ BU TABLOLARLA INTERSECT VE MINUS İŞLEMLERİNİ GERÇEKLEŞTİRELİM
SELECT * FROM DEPT1
INTERSECT
SELECT * FROM DEPT2
ORDER BY 1; -- İKİSİ ARASINDAKİ KESİŞİMİ VERDİ Kİ TAHMİN ETTİĞİMİZ GİBİ 4 DEĞER KARŞIMIZA ÇIKTI ! TERSİ DE AYNISINI ÇIKARIR

-- ŞİMDİ MINUS İŞLEMLERİNE GEÇELİM BURADA SIRALAMA ÖNEMLİ 
SELECT * FROM DEPT1
MINUS
SELECT * FROM DEPT2
ORDER BY 1; -- A NIN B DEN FARKI YANI DEPT1 ' İN DEPT2 DEN FARKINI GÖRMÜŞ OLDUK İKİ DEĞER KARŞIMIZA ÇIKTI

SELECT * FROM DEPT2
MINUS
SELECT * FROM DEPT1
ORDER BY 1; -- BURADAN BİR DEĞER KARŞIMIZA ÇIKMADI DEMEK DEPT 2 DEPT1 İN İÇİNDEYMİŞ
-- NOT ! MINUS , INTERSECT, UNION , VE UNION ALL İŞLEMLERİNİ YAPABİLMEMİZ İÇİN BÖLÜNEN TABLOLARIN KOLONLARI EŞİT OLMALI
-- VE BİRBİRİYLE UYUMLU OLMALIDIR ( AYNI ŞEKİL TABLOLAMA TİPİ)
