-- INNER JOIN GELENEKSEL
-- ISTENILEN KOLONLAR LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME VE CITY
SELECT
E.LAST_NAME,
D.DEPARTMENT_ID,
D.DEPARTMENT_NAME,
L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID
ORDER BY E.LAST_NAME ASC ;
-- BUNU YAPABİLMEK İÇİN ÖNCELİKLE DEPARTMENT_ID KOLONLARINI BAĞLADIK BİRBİRİNE BU SAYEDE EMPLOYEES VE DEPARTMENTS ARASINDA
-- BAĞLANTI KURMUŞ OLDUK. DAHA SONRA DEPARMENT İLE LOCATIONS TABLOSUNU BAĞLAMAMIZ GEREKLİ ORTAK OLAN LOCATION_ID İLE BUNU DA
-- YAPTIĞIMIZDA E DEN L  YE BAĞLANTI KURMUŞ OLUYORUZ ÇÜNKÜ CITY'YE ULAŞMANIN YOLU EMPLOYEES İLE LOCATION BAĞLANTISI