-- INSTR
-- ! EĞER SUBSTR VEYA INSTR ICINE VERİLEN SAYILAR NEGATİF OLURSA TERSTEN SAYMA İŞLEMİ YAPILIR DENK GELEN
-- KISIMDAN BAŞLAR , VİRGÜLDEN SONRAKİ İKİNCİ SAYI İSE KAÇINCI DEĞERİ ALMAMIZI GÖSTERİR.
SELECT INSTR('FERHAT GÜDEK', 'E',1,1) ,
INSTR ('FERHAT GÜDEK','K',1,1),
INSTR ('FERHAT GÜDEK', 'E',1,2),
INSTR ('FERHAT GÜDEK','E',2,1) FROM DUAL ; -- BOŞLUKLARI DA KARAKTER OLARAK SAYIYOR.

SELECT INSTR ('FERHAT GÜDEK','C',1,1) FROM DUAL ; -- EĞER HİÇ GEÇMEZ İSE SIFIR SONUCUNU BİZE DÖNDÜRÜR.