-- LEFT JOIN ANSI
-- REGION_ID, REGION_NAME,COUNTRY_ID,COUNTRY_NAME İLE CITY OLUŞTURULACAK
SELECT R.REGION_ID,R.REGION_NAME,C.COUNTRY_ID,C.COUNTRY_NAME,L.CITY FROM REGIONS R
LEFT OUTER JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
LEFT OUTER JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
ORDER BY 5,1,3 ;
