-- LEFT JOIN GELENKSEL
-- ŞİMDİ REGION_ID, REGION_NAME, COUNTRY_ID, COUNTRY_NAME VE CITY KOLONLARINDAN OLUŞAN BİR TABLO YAPALIM
SELECT R.REGION_ID, R.REGION_NAME, C.COUNTRY_ID, C.COUNTRY_NAME, L.CITY
FROM REGIONS R, COUNTRIES C, LOCATIONS L WHERE R.REGION_ID = C.REGION_ID(+) 
AND C.COUNTRY_ID = L.COUNTRY_ID(+) ORDER BY R.REGION_ID ; 
-- BURADA İLK TARAFTA TABLO SAĞDA KALDIĞI İÇİN YANİ C.REGION_ID KISMINA SAĞDA KALDIĞI İÇİN + İŞARET KOYDUK DİĞER
-- KISMA İSE TABLODA EKSİK OLACAĞINI DÜŞÜNDÜĞÜMÜZ YERE KOYUYORUZ MESELA COUNTRY_ID' E KOYDUĞUMUZ GİBİ