-- NATURAL JOIN
DESC EMPLOYEES;
-- DESC YAPTIKTAN SONRA GÖRDÜK Kİ İKİ TABLODA DA JOB_ID 
-- ORTAK YANİ JOIN İŞLEMİ BUNUN ÜZERİNDEN OLACAK
-- ANSI FORMAT
SELECT EMPLOYEE_ID ,
FIRST_NAME,
JOB_ID,
JOB_TITLE FROM EMPLOYEES NATURAL JOIN JOBS
ORDER BY EMPLOYEE_ID;
-- BURADA JOB_TITLE BAŞTA YOKTU BIZ JOIN YAPARAK GETİRTTİK.
-- GELENEKSEL JOIN
SELECT E.EMPLOYEE_ID,
E.FIRST_NAME,
E.JOB_ID,
J.JOB_TITLE FROM EMPLOYEES E , JOBS J WHERE E.JOB_ID = J.JOB_ID
ORDER BY EMPLOYEE_ID ;
-- BURADAKİ OLAN İSE TÜM BUNLAR NORMALDE EMPLOYEESTEN GELİYORDU O YÜZDEN BİZDE BUNU BELİRTEREK HAREKET
-- EDİYORUZ Kİ DİĞER TABLODAN JOB_TITLE İSTEDİĞİMİZ İÇİN O VE ONU ALDIĞIMIZ YER OLAN JOBS KISMI J OLARAK
-- BELİRLENDİ. NATURAL JOIN İSE AYNI OLAN ZATEN JOB_ID OLDUĞU İÇİN DİREKT ONUN ÜZERİNDEN İLERLİYOR