-- NVL AND NVL2
SELECT FIRST_NAME, COMISSION_PCT, NVL(COMISSION_PCT,0) FROM EMPLOYEES; -- EĞER COM. DEĞERLERİ BOŞ İSE 0 YAZACAK
SELECT FIRST_NAME, COMISSION_PCT, NVL(COMISSION_PCT,'BOS') FROM EMPLOYEES ; -- BURADA HATA VERECEKTİR CÜNKÜ İLK PARAMETRE
--NİN CİNSİ COK ÖNEMLİDİR EĞER SAYISAL İSE YANINA DA SAYISAL YAZILMALI KARAKTER İLE SAYISAL HATA VERDİRİR.
-- NVL (A,B) ŞEKLİNDE İKİ PARAMETRE ALIRKEN NVL2 (A,B,C) ŞEKLİNDE ÜÇ PARAMETRE ALIR FARKLARI NVL2 EĞER DEĞER DOLUYSA
-- B DEKİ DEĞERİ ALIR , BOŞ İSE C DEKİ DEĞERİ ALIR 
SELECT FIRST_NAME, COMISSION_PCT, NVL2(COMISSION_PCT,SALARY*(1+COMISSION_PCT),SALARY) FROM EMPLOYEES;
-- BURADA EĞER DOLUYSA MAAŞ * 1 + COM. YAPTIK EĞER BOŞ İSE DİREKT MAAŞ YAZDIRILMASINI SAĞLADIK.