-- REPLACE
SELECT REPLACE ('FERHAT GÜDEK','FERHAT','F') FROM DUAL; -- F GÜDEK SONUCUNU BİZE DÖNDÜRÜR REPLACE BURADA FERHAT GÜDEK
-- İFADESİNDEKİ FERHAT ' I F İLE DEĞİŞTİR İŞLEMİNİ YAPMIŞTIR.
SELECT FIRST_NAME, JOB_ID, REPLACE(JOB_ID,'IT','BT') YENI_GOSTERIM FROM EMPLOYEES; -- BÖYLECE IT OLAN KISMI BT İLE DEĞİŞTİRMİŞ OLDUK