-- SELF JOIN GELENSEKSEL
-- FIRST_NAME,LAST_NAME,MANAGER_ID VE MANAGER_NAME OLAN TABLO YAPALIM
-- BUNLARIN HEPSİ ZATEN EMPLOYEES DE VAR YANİ SELF JOIN İŞLEMİ GERÇEKLEŞTİRECEĞİZ
SELECT E1.FIRST_NAME,E1.LAST_NAME,E1.MANAGER_ID, E2.FIRST_NAME,E2.LAST_NAME
FROM EMPLOYEES E1, EMPLOYEES E2 WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID 
ORDER BY E1.EMPLOYEE_ID ; 
-- BURADA MANAGER ID İLE EMPLOYEE ID KEY OLDUĞU İÇİN BU ŞEKİLDE GERÇEKLEŞTİRDİK YANİ MANAGER ID MERKEZLİ ŞEKİLDE YAZDIK
-- BU ŞU ŞEKİLDE DE DÜZENLENEİBLİR 
SELECT E1.FIRST_NAME,E1.LAST_NAME,E1.MANAGER_ID, E2.FIRST_NAME,E2.LAST_NAME
FROM EMPLOYEES E1, EMPLOYEES E2 WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID(+)
ORDER BY E1.EMPLOYEE_ID ; -- BU ŞEKİLDE DE HEM SELF JOIN İŞLEMİ HEM DE LEFT JOIN İŞLEMİ YAPMIŞ OLDUK . CONCAT VE ADLANDIRMA 
-- DA YAPILABİLİR.