-- TO CHAR
SELECT SYSDATE FROM DUAL; -- ŞUANKİ TARİHİ GÖSTEREN BİR KOD
-- TO CHAR KULLANIMI
SELECT SYSDATE,
TO_CHAR(SYSDATE,'D')HAFTANINKACINCIGUNU,
TO_CHAR(SYSDATE,'DD')AYINKACINCIGUNU,
TO_CHAR(SYSDATE,'DDD')YILINKACINCIGUNU,
TO_CHAR(SYSDATE,'DAY')GUNISMI,
TO_CHAR(SYSDATE,'DY')KISAGUNISMI,
TO_CHAR(SYSDATE,'W')AYINKACINCIHAFTASI,
TO_CHAR(SYSDATE,'WW')YILINKACINCIHAFTASI ,
TO_CHAR(SYSDATE,'MM')AYNUMARASI,
TO_CHAR(SYSDATE,'MON')AYISMI,
TO_CHAR(SYSDATE,'YYYY')YIL,
TO_CHAR(SYSDATE,'YEAR')YILOKUNUS,
TO_CHAR(SYSDATE,'HH24:MI:SS')SAATDAKIKASANIYE,
TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS')AYRINTILIYIL
FROM DUAL;