-- UPDATE ILE ESKI VERI DEGERLERINE BENZETIM
-- 60 NO'LU BÖLÜMDE ÇALIŞANLARIN MAAŞINI ZAM YAPMADAN ÖNCEKİ HALİNE UPDATE EDELİM
-- BUNUN İÇİN EMPLOYEES DEĞERİNİ DİĞER TABLOYA EMPLOYEES_COPY UPDATE EDECEĞİZ
SELECT EMPLOYEE_ID, SALARY,COMISSION_PCT FROM EMPLOYEES_COPY WHERE DEPARTMENT_ID = 60;
UPDATE EMPLOYEES_COPY A SET
A.SALARY = (SELECT B.SALARY FROM EMPLOYEES B
WHERE A.EMPLOYEE_ID = B.EMPLOYEE_ID )
WHERE A.DEPARTMENT_ID = 60;
COMMIT ;
-- COMMIT YERİNE DİREKT CREATE , ALTER VEYA DROP YAPARAK DA KALICI KAYIT YAPABİLİRDİK DDL DML'İ COMMİT EDER.