-- UNION ILE UNIONALL
SELECT * FROM DEPARTMENTS ORDER BY DEPARTMENT_ID;
CREATE TABLE DEPT1
AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID <= 90;

CREATE TABLE DEPT2
AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID >= 40;
-- BU ŞEKİLDE TABLOYU İKİYE BÖLÜYORUZ DEPT 1 VE İKİ DİYE
-- ŞİMDİ İKİ TABLOYU UNION VE UNION ALL İLE BİRLEŞTİRME İŞLEMLERİNİ GERÇEKLEŞTİRELİM
SELECT * FROM DEPT1
UNION
SELECT * FROM DEPT2 -- ASLINDA BU ŞEKİLDE BİRLEŞİR ANCAK ORDER BY 1 İLE SIRALI ŞEKİLDE GERÇEKLEŞTİRİLİR
ORDER BY 1; -- UNION OLARAK BİRLEŞTİRDİĞİMİZ İÇİN MATEMATİKTEKİ KÜMELER OP. GİBİ OLANLARI TEKRAR SAYMADI 

SELECT * FROM DEPT1
UNION ALL
SELECT * FROM DEPT2
ORDER BY 1; -- BU İSE OLANLARI DA TEKRAR SAYARAK BİRLEŞTİRDİ Kİ UNION DA ÇIKAN 6 SAYISI BURADA 10 ELEMANA YÜKSELDİ.
