-- UPDATE_SEV_SUBQUERY
-- 60 NO'LU BOLUMDE CALISANLARIN MAAŞLARINI 50 NO'LU BÖOLUMDE ÇALIŞANLARIN EN BÜYÜK MAAŞINA EŞİTLE
SELECT DEPARTMENT_ID,LAST_NAME,SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID =60;
UPDATE EMPLOYEES
SET
SALARY = (
    SELECT MAX(SALARY)FROM EMPLOYEES WHERE DEPARTMENT_ID =50
) WHERE DEPARTMENT_ID = 60 ;
