-- WHERE_ICINDE_SUBQUERIES
-- LEX ISIMLI KISIDEN SONRA ISE GIRENLERI LİSTELEYELİM
SELECT HIRE_DATE FROM EMPLOYEES WHERE FIRST_NAME = 'Lex';
SELECT FIRST_NAME, TO_CHAR(HIRE_DATE,'DD/MM/YYYY')TARIH FROM EMPLOYEES
WHERE HIRE_DATE > TO_DATE('13/01/2018','DD/MM/YYYY'); -- BU ŞEKİLDE KAYITLARI GÖSTERMİŞ OLDUK 
-- SIMDI WHERE ICINDE SUBQUERIES YAPARAK GÖSTERELİM
SELECT FIRST_NAME, TO_CHAR(HIRE_DATE,'DD/MM/YYYY')TARIH FROM EMPLOYEES
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM EMPLOYEES WHERE FIRST_NAME='Lex'); -- BU DA AYNI CEVABI VERMIŞ OLDU