-- WHERE_ICINDE_SUBQUERY
-- UNVANI ERNST İLE AYNI OLUP, ERNSTDEN DAHA FAZLA MAAŞ ALANLARI LİSTELE
-- NORMAL ŞEKİLDE YAPARSAK
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES
WHERE LAST_NAME ='Ernst'; -- EĞER AYNI ISIMDEN OLSAYDI BURAYA AND İLE EMPLOYEE_ID EKLERDİK
SELECT LAST_NAME, JOB_ID,SALARY FROM EMPLOYEES WHERE JOB_ID ='IT_PROG' AND SALARY >6000;

-- ŞİMDİ WHERE İÇİNDE SUBQUERY İLE YAPALIM
SELECT LAST_NAME,JOB_ID,SALARY FROM EMPLOYEES WHERE SALARY > (
    SELECT SALARY FROM EMPLOYEES WHERE LAST_NAME = 'Ernst'
)
AND JOB_ID = (
    SELECT JOB_ID FROM EMPLOYEES WHERE LAST_NAME = 'Ernst' 
); -- BU KODUN HEPSİNİ BİR ANDA ÇALIŞTIRMAMIZA RAĞMEN İSTENİLEN SONUCU VERECEKTİR , DİĞERİNİ TEKER TEKER ÇAILIŞTIRDIK