--DELETE_SEV_SUBQUERY
-- SOYISMI YANI LAST_NAME 'İ TEKRAR EDEN KAYITLARDAN SADECE BİR TANESİ KALSIN DİĞERLERİ SİLİNSİN
SELECT ROWID,LAST_NAME,SALARY FROM EMPLOYEES ; -- BU KONUDAN BAGIMSIZ ADRES KOLON NUMARALARINI GÖSTERİR
SELECT LAST_NAME,COUNT(*)FROM EMPLOYEES GROUP BY LAST_NAME HAVING COUNT(*)> 1;
DELETE FROM EMPLOYEES
WHERE ROWID NOT IN
(SELECT MAX(ROWID)FROM EMPLOYEES GROUP BY LAST_NAME);
-- BU ŞEKİLDE İSTENİLEN SONUÇ ELDE EDİLECEKTİR