--HAVING_SEV_SUBQUERY
SELECT DEPARTMENT_ID, MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY)>(SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID =60 );
SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID =60;
-- HAVING YAZIYORUZ CUNKU FILTELEME OLAYLARINDA KULLANILIR WHERE İLE HATA ALINACAKTIR.