--MIN,MAX..GROUPBY
SELECT DEPARTMENT_ID,
ROUND(AVG(SALARY),2),-- ORTALAMA MAAŞI VERİR
MAX(SALARY),-- MAX MAAŞI VERİR
MIN(SALARY),-- MIN MAAŞI VERİR
SUM(SALARY),-- TOPLAM MAAŞI VERİR
COUNT(SALARY),-- AYNI MAAŞI ALAN KİŞİLERİN SAYISINI GÖSTERİR
ROUND(VARIANCE(SALARY),2) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT (SALARY)>1  ORDER BY DEPARTMENT_ID; 
-- ROUND(AGDSG,2) YAPTIĞIMIZDA DEĞERİ YUVARLAR VE İKİ HANELİ ŞEKİLDE BİZE DEĞER DÖNDÜRÜR
-- TÜM SALARYLER MAX MIN SUM GİBİ BİR FONKSİYON İLE BAĞLIYDI ANCAK DEPARTMENT_ID YALINDI Kİ BU BİZE HATA DÖNDÜRÜR ONUN 
-- ÇALIŞMASI İÇİN GRUPLAMA YAPMAMIZ GEREKLİYDİ Kİ GROUP BY İLE BUNU YAPTIK . BURADA AMACIMIZ TÜM MAAŞLARI GÖRMEK YERİNE 
-- BÖLÜM OLARAK GÖRELİM İSTEDİK Kİ BU AYRIMI DEPARMENT_ID İLE YAPTIK
-- EĞER DİREKT ÖRNEĞİN 90 ID Lİ KİŞİYİ İSTESEYDİK WHERE DEP.ID = 90 YAPARDIK ANCAK HAVİNG BİR FİLTRELEME FONKSİYONUDUR
-- BİZE YAPTIĞIMIZ İŞLEMLERİ FİLTRELEREYEK ÖRNEĞİN COUNT MAAŞI BİR'DEN DAHA BÜYÜK DEĞERLERİ İSTEDİĞİMİZDE KULLANACAĞIMIZ FONKSİYONDUR.