--WHERE_ICINDE_SUBQUERY3
--EN DUSUK MAAS ALAN KISIYI BULALIM LAST_NAME,JOB_ID, SALARY
-- BUNU İLK BASTA NORMAL YOL İLE YAPALIM
SELECT MIN (SALARY) FROM EMPLOYEES ; 
SELECT LAST_NAME,JOB_ID, SALARY FROM EMPLOYEES WHERE SALARY = 6000; -- EN DUSUK MAAS ALAN KISIYI BULDUK

-- SIMDI WHERE ICINDE SUBQUERY İLE YAPALIM
SELECT LAST_NAME,JOB_ID,SALARY, (
    SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
)AS"BOLUM ADI" FROM EMPLOYEES E WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);
-- BURADA FARKLI OLARAK BOLUM ADINI DA GETİRMİŞ OLDUK EK BİR SELECT İŞLEMİ YAPARAK
