ALTER TABLE REGIONS ADD(
    CONSTRAINT reg_id_pk PRIMARY KEY (REGION_ID)
);
ALTER TABLE COUNTRIES ADD(
    CONSTRAINT countr_reg_fk FOREIGN KEY (REGION_ID) REFERENCES REGIONS (REGION_ID)
);
ALTER TABLE COUNTRIES ADD(
    CONSTRAINT countr_id_pk PRIMARY KEY (COUNTRY_ID)
);
ALTER TABLE LOCATIONS ADD(
    CONSTRAINT loc_count_fk FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID)
);
ALTER TABLE LOCATIONS ADD(
    CONSTRAINT loc_id_pk PRIMARY KEY (LOCATION_ID)
);
ALTER TABLE DEPARTMENTS ADD(
    CONSTRAINT dep_id_pk PRIMARY KEY (DEPARTMENT_ID) ,
    CONSTRAINT dep_loc_fk FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID)
);
ALTER TABLE DEPARTMENTS ADD LOCATION_ID NUMBER(4);
ALTER TABLE JOBS ADD(
    CONSTRAINT job_id_pk PRIMARY KEY (JOB_ID)
);
ALTER TABLE EMPLOYEES ADD DEPARTMENT_ID NUMBER(2);
ALTER TABLE EMPLOYEES ADD(
    CONSTRAINT emp_id_pk PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT emp_dep_fk FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID),
    CONSTRAINT emp_job_fk FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
    CONSTRAINT emp_man_fk FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);
ALTER TABLE DEPARTMENTS ADD(
    CONSTRAINT dep_man_fk FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);
ALTER TABLE JOB_HISTORY ADD(
    CONSTRAINT jhist_emp_id_st_date_pk PRIMARY KEY (EMPLOYEE_ID,START_DATE),
    CONSTRAINT jhist_job_id_fk FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
    CONSTRAINT jhist_emp_id_fk FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT jhist_dept_id_fk FOREIGN KEY (DEPARTMENT_ID)REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);
