DESC REGIONS;
INSERT INTO REGIONS VALUES (1,'EUROPA');
ALTER TABLE REGIONS ADD POPULATE NUMBER(15);
INSERT INTO REGIONS (REGION_ID,REGION_NAME) VALUES (2,'ASIA'); -- EKLEDİĞİMİZ DEĞERLERİN NE OLDUĞU
ALTER TABLE REGIONS DROP COLUMN POPULATE; -- BURADAN EKLEDİĞİMİZ KOLONU SİLİYORUZ
-- YANİ REGIONS'DAN DROP COLUMN YAPARAK POPULATE'İ SİLİYORUZ.