DESC COUNTRIES;
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID) VALUES ('TR','TURKIYE','1');
-- BURADA REGION ID BİLGİSİ DESC İLE GÖZÜKMEDİ AYRI BİR SAYFADA SELECT YAPARAK KONTOL ETTİK Kİ 
-- DOĞRU DEĞER GİRELİM DİYE EĞER YANLIŞ DEĞER GİRDİĞİMİZDE HATA ALIRIZ.
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID) VALUES ('KT','KKTC','1');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_NAME,REGION_ID)VALUES ('IT','ITALY','1');
SELECT * FROM COUNTRIES; -- BURADAKİ YILDIZ BOŞLUKLU OLMALI YOKSA HATA VERİYOR