SELECT * FROM EMPLOYEES; -- BİR TABLODAKİ TÜM KOLONLARIN SORGULANMASI
SELECT MANAGER_ID, FIRST_NAME,LAST_NAME,EMAIL FROM EMPLOYEES; -- BİR TABLODAKİ BELİRLİ KOLONLARIN SORGULANMASI
-- ÜSTEKİ SORGUDAKİ SIRALAMA ÖNEMLİ BİZ MESELA MANAGER ID 'İ BAŞA ALARAK BİR SONUÇ GETİRTTİK.
SELECT MANAGER_ID AS MGR,FIRST_NAME ADI, LAST_NAME SOYISMI, EMAIL EPOSTA FROM EMPLOYEES;
-- BURADA İSE SORGU KOLONLARININ BAŞLIKLARINI DEĞİŞTİREREK YAPTIK.
SELECT MANAGER_ID"MUDUR NO", FIRST_NAME"ILK ADI",LAST_NAME"SOY ISMI",EMAIL"E POSTA" FROM EMPLOYEES;
-- EĞER BİRDEN FAZLA İSİM OLACAKSA TIRNAK İÇİNDE OLARAK YAZILIR 
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 60;-- 60 NO'LU BÖLÜMDE ÇALIŞANLARIN LİSTESİ
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 60 OR DEPARTMENT_ID = 80;-- HEM 60 HEM 80
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (60,80); -- BU DA IN İLE GÖSTERİMİ
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE 'A%' ; -- SOY ISMI A İLE BAŞLAYAN ELEMANLAR
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%KE%'; -- SOY ADINDA KE İFADESİ GEÇEN ELEMANLAR
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '_u_s%';-- İKİNCİ HARFİ U DÖRDÜNCÜ HARFİ S OLAN KİŞİLER
SELECT * FROM EMPLOYEES WHERE SALARY > 5000 AND COMISSION_PCT IS NOT NULL ; 
-- MAAŞI 5 K ÜSTÜ OLUP KOMİSYON ORANI BOŞ OLMAYANLARIN LİSTESİNİ GÖSTERİR.